<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class StoreUserRequest extends FormRequest
{

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            //
            'first_name' => 'required|string|regex:/^[A-ZА-ЯЁ][a-zа-яё]*$/u',
            'last_name' => 'required|string|regex:/^[A-ZА-ЯЁ][a-zа-яё]*$/u',
            'patronymic' => 'required|string|regex:/^[A-ZА-ЯЁ][a-zа-яё]*$/u',
            'email' => 'required|string|email|unique:users,email',
            'password' => 'required|string|min:3|regex:/(?=.*[a-zа-яё])(?=.*[A-ZА-ЯЁ])(?=.*\d).+$/u',
            'birth_date' => 'required|string',
        ];
    }
    public function messages()
    {
        return [
            'first_name.regex' => 'The first name must start with a capital letter.',
            'last_name.regex' => 'The last name must start with a capital letter.',
            'patronymic.regex' => 'The patronymic must start with a capital letter.',
            'password.regex' => 'The password must contain at least one uppercase letter, one lowercase letter, and one number.',
        ]; // TODO: Change the autogenerated stub
    }
}
